#! /hint/sh

NINJAFLAGS="-d stats -w phonycycle=err"

if ! [ -z "${_march}" ]; then
    march="-march=${_march}"
    mtune="-mtune=${_march}"
fi

if [ ! -z "${_avx}" ]; then
    avx_instructions="-mprefer-vector-width=${_avx}"
fi

export CFLAGS="${march} ${mtune} -O3 -flto=thin -falign-functions=32 -fno-semantic-interposition ${avx_instructions} -mfpmath=sse -msse2"
export CXXFLAGS="${CFLAGS}"
export LDFLAGS="-Wl,-O3,--sort-common,--as-needed,-z,relro,-z,now"
