#! /hint/sh

_no_pgo_build()
{
    meson setup mesa _build                                                                 \
        --strip                                                                             \
        -D b_ndebug='true'                                                                  \
        -D b_lto='true'                                                                     \
        -D buildtype='plain'                                                                \
        --wrap-mode='nofallback'                                                            \
        -D prefix='/usr'                                                                    \
        -D sysconfdir='/etc'                                                                \
        -D platforms='x11,wayland'                                                          \
        -D dri-drivers='i915,i965,r200,r100,nouveau'                                        \
        -D gallium-drivers='r300,r600,radeonsi,nouveau,svga,swrast,virgl,iris,zink,crocus'  \
        -D vulkan-drivers='amd,intel,swrast,virtio-experimental'                            \
        -D dri3='enabled'                                                                   \
        -D egl='enabled'                                                                    \
        -D gallium-extra-hud='true'                                                         \
        -D gallium-nine='true'                                                              \
        -D gallium-omx='bellagio'                                                           \
        -D gallium-va='enabled'                                                             \
        -D gallium-vdpau='enabled'                                                          \
        -D gallium-xa='enabled'                                                             \
        -D gallium-xvmc='disabled'                                                          \
        -D gbm='enabled'                                                                    \
        -D gles1='disabled'                                                                 \
        -D gles2='enabled'                                                                  \
        -D glvnd='true'                                                                     \
        -D glx='dri'                                                                        \
        -D libunwind='enabled'                                                              \
        -D llvm='enabled'                                                                   \
        -D lmsensors='enabled'                                                              \
        -D osmesa='true'                                                                    \
        -D shared-glapi='enabled'                                                           \
        -D gallium-opencl='icd'                                                             \
        -D valgrind='disabled'                                                              \
        -D vulkan-layers='device-select,overlay'                                            \
        -D tools=[]                                                                         \
        -D zstd='enabled'                                                                   \
        -D video-codecs=vc1dec,h264dec,h264enc,h265dec,h265enc                              \
        -D microsoft-clc='disabled'

    meson configure --no-pager _build

    ninja $NINJAFLAGS -C _build
}

_generate_pgo_build()
{
    meson setup mesa "$pgo_build_dir"                                                       \
        --strip                                                                             \
        -D b_ndebug='true'                                                                  \
        -D b_lto='true'                                                                     \
        -D b_pgo='generate'                                                                 \
        -D buildtype='plain'                                                                \
        --wrap-mode='nofallback'                                                            \
        -D prefix='/usr'                                                                    \
        -D sysconfdir='/etc'                                                                \
        -D platforms='x11,wayland'                                                          \
        -D dri-drivers='i915,i965,r200,r100,nouveau'                                        \
        -D gallium-drivers='r300,r600,radeonsi,nouveau,svga,swrast,virgl,iris,zink,crocus'  \
        -D vulkan-drivers='amd,intel,swrast,virtio-experimental'                            \
        -D dri3='enabled'                                                                   \
        -D egl='enabled'                                                                    \
        -D gallium-extra-hud='true'                                                         \
        -D gallium-nine='true'                                                              \
        -D gallium-omx='bellagio'                                                           \
        -D gallium-va='enabled'                                                             \
        -D gallium-vdpau='enabled'                                                          \
        -D gallium-xa='enabled'                                                             \
        -D gallium-xvmc='disabled'                                                          \
        -D gbm='enabled'                                                                    \
        -D gles1='disabled'                                                                 \
        -D gles2='enabled'                                                                  \
        -D glvnd='true'                                                                     \
        -D glx='dri'                                                                        \
        -D libunwind='enabled'                                                              \
        -D llvm='enabled'                                                                   \
        -D lmsensors='enabled'                                                              \
        -D osmesa='true'                                                                    \
        -D shared-glapi='enabled'                                                           \
        -D gallium-opencl='icd'                                                             \
        -D valgrind='disabled'                                                              \
        -D vulkan-layers='device-select,overlay'                                            \
        -D tools=[]                                                                         \
        -D zstd='enabled'                                                                   \
        -D video-codecs=vc1dec,h264dec,h264enc,h265dec,h265enc                              \
        -D microsoft-clc='disabled'

    meson configure --no-pager "$pgo_build_dir"

    ninja $NINJAFLAGS -C "$pgo_build_dir"
}

_use_pgo_build()
{
    meson setup mesa "$pgo_build_dir"                                                       \
        --strip                                                                             \
        -D b_ndebug='true'                                                                  \
        -D b_lto='true'                                                                     \
        -D b_pgo='use'                                                                      \
        -D buildtype='plain'                                                                \
        --wrap-mode='nofallback'                                                            \
        -D prefix='/usr'                                                                    \
        -D sysconfdir='/etc'                                                                \
        -D platforms='x11,wayland'                                                          \
        -D dri-drivers='i915,i965,r200,r100,nouveau'                                        \
        -D gallium-drivers='r300,r600,radeonsi,nouveau,svga,swrast,virgl,iris,zink,crocus'  \
        -D vulkan-drivers='amd,intel,swrast,virtio-experimental'                            \
        -D dri3='enabled'                                                                   \
        -D egl='enabled'                                                                    \
        -D gallium-extra-hud='true'                                                         \
        -D gallium-nine='true'                                                              \
        -D gallium-omx='bellagio'                                                           \
        -D gallium-va='enabled'                                                             \
        -D gallium-vdpau='enabled'                                                          \
        -D gallium-xa='enabled'                                                             \
        -D gallium-xvmc='disabled'                                                          \
        -D gbm='enabled'                                                                    \
        -D gles1='disabled'                                                                 \
        -D gles2='enabled'                                                                  \
        -D glvnd='true'                                                                     \
        -D glx='dri'                                                                        \
        -D libunwind='enabled'                                                              \
        -D llvm='enabled'                                                                   \
        -D lmsensors='enabled'                                                              \
        -D osmesa='true'                                                                    \
        -D shared-glapi='enabled'                                                           \
        -D gallium-opencl='icd'                                                             \
        -D valgrind='disabled'                                                              \
        -D vulkan-layers='device-select,overlay'                                            \
        -D tools=[]                                                                         \
        -D zstd='enabled'                                                                   \
        -D video-codecs=vc1dec,h264dec,h264enc,h265dec,h265enc                              \
        -D microsoft-clc='disabled'

    meson configure --no-pager "$pgo_build_dir"

    ninja $NINJAFLAGS -C "$pgo_build_dir"
}
