#! /hint/sh

_remove_build_dir()
{
    cd "${srcdir}"

    if [ -d _build ]; then
        rm -rf _build
    fi
}

_remove_pgo_build_dir()
{
    if [ "${PGO}" = "generate" ]; then
        if [ -d "${pgo_build_dir}" ]; then
            rm -rf "${pgo_build_dir}"
        fi
    fi
}

_remove_unneeded_files()
{
    rm -rf "${pkgdir}/usr/bin/mesa-overlay-control.py"
    rm -rf "${pkgdir}/usr/bin"
}

_remove_unneeded_pgo_build()
{
    find "${pgo_build_dir}" -maxdepth 1 -type f -exec rm -rf {} \;
    find "${pgo_build_dir}/"* -maxdepth 0 -type d ! -name "src" -exec rm -rf {} \;
}
