#! /hint/sh

_ninja_install()
{
    if [ "$PGO" != "off" ]; then
        DESTDIR="$pkgdir" ninja $NINJAFLAGS -C "$pgo_build_dir" install
    else
        DESTDIR="$pkgdir" ninja $NINJAFLAGS -C _build install
    fi
}
