#! /hint/sh

_remove_build_dir()
{
    cd "${srcdir}"

    if [ -d _build ]; then
        rm -rf _build
    fi
}

_remove_pgo_build_dir()
{
    if [ "${_pgo}" = "generate" ]; then
        if [ -d "${_pgo_build_dir}" ]; then
            rm -rf "${_pgo_build_dir}"
        fi
    fi
}

_remove_unneeded_files()
{
    if [ -d "${pkgdir}" ]; then
        rm -rf "${pkgdir}/usr/bin/mesa-overlay-control.py"
        rm -rf "${pkgdir}/usr/bin"
    fi
}

_remove_unneeded_pgo_build()
{
    if [ -d "${_pgo_build_dir}" ]; then
        find "${_pgo_build_dir}" -maxdepth 1 -type f -exec rm -rf {} \;
        find "${_pgo_build_dir}/"* -maxdepth 0 -type d ! -name "src" -exec rm -rf {} \;
    fi
}
