#! /hint/sh

_set_number_of_fds()
{
    ulimit -n 8192
}

_native_clang()
{
	cat <<-EOF > "${_native_file}"
		#! /hint/toml

		[binaries]
		c = ['/usr/bin/clang', '-mfpmath=sse']
		cpp = ['/usr/bin/clang++', '-mfpmath=sse']
		ar = '/usr/bin/llvm-ar'
		strip = '/usr/bin/llvm-strip'
		llvm-config = '/usr/bin/llvm-config'
		pkg-config = '/usr/bin/pkg-config'

		[built-in options]
		c_args = [ ${_c_args[@]} ]
		c_link_args = [ ${_c_link_args[@]} ]
		cpp_args = [ ${_c_args[@]} ]
		cpp_link_args = [ ${_c_link_args[@]} ]
		objc_args = []
		objc_link_args = [ ${_c_link_args[@]} ]
		objcpp_args = []
		objcpp_link_args = [ ${_c_link_args[@]} ]
		fortran_args = [ '-O3' ]
		fortran_link_args =[ ${_c_link_args[@]} ]

		[host_machine]
		system = '${_host_machine_os}'
		cpu_family = '${_cpu_architecture}'
		cpu = '${_cpu_microarchitecture}'
		endian = '${_endianess}'
	EOF
}

_native_gcc()
{
	cat <<-EOF > "${_native_file}"
		#! /hint/toml

		[binaries]
		c = ['/usr/bin/gcc', '-mfpmath=sse']
		cpp = ['/usr/bin/g++', '-mfpmath=sse']
		ar = '/usr/bin/ar'
		strip = '/usr/bin/strip'
		llvm-config = '/usr/bin/llvm-config'
		pkg-config = '/usr/bin/pkg-config'

		[built-in options]
		c_args = [ ${_c_args[@]} ]
		c_link_args = [ ${_c_link_args[@]} ]
		cpp_args = [ ${_c_args[@]} ]
		cpp_link_args = [ ${_c_link_args[@]} ]
		objc_args = []
		objc_link_args = [ ${_c_link_args[@]} ]
		objcpp_args = []
		objcpp_link_args = [ ${_c_link_args[@]} ]
		fortran_args = [ '-O3' ]
		fortran_link_args =[ ${_c_link_args[@]} ]

		[host_machine]
		system = '${_host_machine_os}'
		cpu_family = '${_cpu_architecture}'
		cpu = '${_cpu_microarchitecture}'
		endian = '${_endianess}'
	EOF
}

_write_native_file()
{
    if ! [ -z "${_cpu_microarchitecture}" ]; then
        march="'-march=${_cpu_microarchitecture}',"
        mtune="'-mtune=${_cpu_microarchitecture}',"
    fi

    if [ ! -z "${_avx}" ]; then
        avx_instructions="'-mprefer-vector-width=${_avx}',"
    fi

    _c_args=(
        "${march}"
        "${mtune}"
        "'-O3',"
        "'-falign-functions=32',"
        "${avx_instructions}"
    )
    _c_link_args=(
        "${_c_args[@]}"
        "'-Wl,-O3',"
        "'-Wl,--as-needed',"
        "'-Wl,--sort-common',"
    )

    if [ "${_use_clang}" ]; then
        export _native_file="${startdir}/clang.native"

        _c_args+=("'-flto=thin',")
        _c_link_args+=(
            "'-flto=thin',"
            "'-fuse-ld=lld',"
            "'-Wl,--thinlto-jobs=$(nproc)',"
        )

        _native_clang
    else
        export _native_file="${startdir}/gcc.native"

        _c_args+=("'-flto',")
        _c_link_args+=("'-flto',")

        _native_gcc
    fi
}

_no_pgo_build()
{
    meson setup mesa _build                                                                             \
        --strip                                                                                         \
        --native-file "${_native_file}"                                                                 \
        -D b_ndebug='true'                                                                              \
        -D b_lto='true'                                                                                 \
        -D buildtype='plain'                                                                            \
        --wrap-mode='nofallback'                                                                        \
        -D prefix='/usr'                                                                                \
        -D sysconfdir='/etc'                                                                            \
        -D platforms='x11,wayland'                                                                      \
        -D dri-drivers='i915,i965,r200,r100,nouveau'                                                    \
        -D gallium-drivers='r300,r600,radeonsi,nouveau,svga,softpipe,llvmpipe,virgl,iris,zink,crocus'   \
        -D vulkan-drivers='amd,intel,swrast,virtio-experimental'                                        \
        -D egl='enabled'                                                                                \
        -D gallium-extra-hud='true'                                                                     \
        -D gallium-va='enabled'                                                                         \
        -D gallium-vdpau='enabled'                                                                      \
        -D gallium-xa='enabled'                                                                         \
        -D gallium-xvmc='disabled'                                                                      \
        -D gbm='enabled'                                                                                \
        -D gles1='disabled'                                                                             \
        -D gles2='enabled'                                                                              \
        -D glvnd='enabled'                                                                              \
        -D glx='dri'                                                                                    \
        -D libunwind='enabled'                                                                          \
        -D llvm='enabled'                                                                               \
        -D lmsensors='enabled'                                                                          \
        -D osmesa='true'                                                                                \
        -D shared-glapi='enabled'                                                                       \
        -D gallium-opencl='icd'                                                                         \
        -D valgrind='disabled'                                                                          \
        -D vulkan-layers='device-select,overlay'                                                        \
        -D tools=[]                                                                                     \
        -D zstd='enabled'                                                                               \
        -D video-codecs=vc1dec,h264dec,h264enc,h265dec,h265enc,av1dec,av1enc,vp9dec                     \
        -D microsoft-clc='disabled'

    meson configure --no-pager _build

    ninja ${NINJAFLAGS} -C _build
}

_generate_pgo_build()
{
    meson setup mesa "${_pgo_build_dir}"                                                                \
        --strip                                                                                         \
        --native-file "${_native_file}"                                                                 \
        -D b_ndebug='true'                                                                              \
        -D b_lto='true'                                                                                 \
        -D b_pgo='generate'                                                                             \
        -D buildtype='plain'                                                                            \
        --wrap-mode='nofallback'                                                                        \
        -D prefix='/usr'                                                                                \
        -D sysconfdir='/etc'                                                                            \
        -D platforms='x11,wayland'                                                                      \
        -D dri-drivers='i915,i965,r200,r100,nouveau'                                                    \
        -D gallium-drivers='r300,r600,radeonsi,nouveau,svga,softpipe,llvmpipe,virgl,iris,zink,crocus'   \
        -D vulkan-drivers='amd,intel,swrast,virtio-experimental'                                        \
        -D egl='enabled'                                                                                \
        -D gallium-extra-hud='true'                                                                     \
        -D gallium-va='enabled'                                                                         \
        -D gallium-vdpau='enabled'                                                                      \
        -D gallium-xa='enabled'                                                                         \
        -D gallium-xvmc='disabled'                                                                      \
        -D gbm='enabled'                                                                                \
        -D gles1='disabled'                                                                             \
        -D gles2='enabled'                                                                              \
        -D glvnd='enabled'                                                                              \
        -D glx='dri'                                                                                    \
        -D libunwind='enabled'                                                                          \
        -D llvm='enabled'                                                                               \
        -D lmsensors='enabled'                                                                          \
        -D osmesa='true'                                                                                \
        -D shared-glapi='enabled'                                                                       \
        -D gallium-opencl='icd'                                                                         \
        -D valgrind='disabled'                                                                          \
        -D vulkan-layers='device-select,overlay'                                                        \
        -D tools=[]                                                                                     \
        -D zstd='enabled'                                                                               \
        -D video-codecs=vc1dec,h264dec,h264enc,h265dec,h265enc,av1dec,av1enc,vp9dec                     \
        -D microsoft-clc='disabled'

    meson configure --no-pager "${_pgo_build_dir}"

    ninja ${NINJAFLAGS} -C "${_pgo_build_dir}"
}

_use_pgo_build()
{
    meson setup mesa "${_pgo_build_dir}"                                                                \
        --strip                                                                                         \
        --native-file "${_native_file}"                                                                 \
        -D b_ndebug='true'                                                                              \
        -D b_lto='true'                                                                                 \
        -D b_pgo='use'                                                                                  \
        -D buildtype='plain'                                                                            \
        --wrap-mode='nofallback'                                                                        \
        -D prefix='/usr'                                                                                \
        -D sysconfdir='/etc'                                                                            \
        -D platforms='x11,wayland'                                                                      \
        -D dri-drivers='i915,i965,r200,r100,nouveau'                                                    \
        -D gallium-drivers='r300,r600,radeonsi,nouveau,svga,softpipe,llvmpipe,virgl,iris,zink,crocus'   \
        -D vulkan-drivers='amd,intel,swrast,virtio-experimental'                                        \
        -D egl='enabled'                                                                                \
        -D gallium-extra-hud='true'                                                                     \
        -D gallium-va='enabled'                                                                         \
        -D gallium-vdpau='enabled'                                                                      \
        -D gallium-xa='enabled'                                                                         \
        -D gallium-xvmc='disabled'                                                                      \
        -D gbm='enabled'                                                                                \
        -D gles1='disabled'                                                                             \
        -D gles2='enabled'                                                                              \
        -D glvnd='enabled'                                                                              \
        -D glx='dri'                                                                                    \
        -D libunwind='enabled'                                                                          \
        -D llvm='enabled'                                                                               \
        -D lmsensors='enabled'                                                                          \
        -D osmesa='true'                                                                                \
        -D shared-glapi='enabled'                                                                       \
        -D gallium-opencl='icd'                                                                         \
        -D valgrind='disabled'                                                                          \
        -D vulkan-layers='device-select,overlay'                                                        \
        -D tools=[]                                                                                     \
        -D zstd='enabled'                                                                               \
        -D video-codecs=vc1dec,h264dec,h264enc,h265dec,h265enc,av1dec,av1enc,vp9dec                     \
        -D microsoft-clc='disabled'

    meson configure --no-pager "${_pgo_build_dir}"

    ninja ${NINJAFLAGS} -C "${_pgo_build_dir}"
}
