#! /hint/sh

_ninja_install()
{
    if [ "${_pgo}" != "off" ]; then
        DESTDIR="${pkgdir}" ninja ${NINJAFLAGS} -C "${_pgo_build_dir}" install
    else
        DESTDIR="${pkgdir}" ninja ${NINJAFLAGS} -C _build install
    fi
}
